# Generated by Django 2.2.10 on 2020-03-05 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import weblog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(editable=False, null=True)),
                ('blog_name', models.TextField()),
                ('custom_header_image_path', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            bases=(models.Model, weblog.models.Feedable),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(editable=False, null=True)),
                ('title', models.TextField()),
                ('posted', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('password', models.TextField(blank=True, null=True)),
                ('passhash', models.TextField(blank=True, editable=False, null=True)),
                ('content_markdown', weblog.models.BlogPostField(default='')),
                ('content_rendered', models.TextField(editable=False, null=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weblog.Blog')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            bases=(models.Model, weblog.models.Feedable),
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content_markdown', models.TextField(default='')),
                ('content_rendered', models.TextField(editable=False, null=True)),
                ('blog_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weblog.BlogPost')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Language')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='weblog.Topic'),
        ),
    ]
