# Generated by Django 2.2.10 on 2020-03-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover_static_url', models.TextField(blank=True, default='images/portfolio_default_cover.png')),
                ('category', models.TextField(blank=True, null=True)),
                ('description_markdown', models.TextField(blank=True, null=True)),
                ('description_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weblog.BlogPost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
