# Generated by Django 2.2.10 on 2020-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
