# Generated by Django 2.2.10 on 2020-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_portfolioproject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='cover_static_url',
            field=models.TextField(blank=True, default='images/portfolio_default_cover.jpg'),
        ),
    ]
