# Generated by Django 2.2.10 on 2020-03-29 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_public_listed', models.BooleanField(default=False)),
                ('access_option', models.IntegerField(choices=[(0, 'Everyone Can Access'), (1, 'Need Login'), (2, 'Creator Only'), (3, 'Superusers Only')], default=0)),
                ('encrypted_id', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
